# 07 - NumPy

## 013 Exercise Nut Butter Store Sales

### Dot product example (nut butter sales)

In [37]:
import numpy as np
import pandas as pd

In [38]:
#1) Number of jars sold
np.random.seed(0)
product_sold = np.random.randint(20, size=(5, 3))
product_sold

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [39]:
#2) Creating a weekly_sales dataframe: i.e putting the above product_sold in a table format
weekly_sales = pd.DataFrame(product_sold, index=["Mon", "Tues", "Wed", "Thurs", "Fri"], 
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

       Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [40]:
#3) Create prices array: i.e an array that has the price for each of Almond butter, 
# Peanut butter and Cashew butter, so we can compute the total sold for that week
prices_array = np.array([10, 8, 12])
prices_array

array([10,  8, 12])

In [41]:
# 4) Create butter_prices dataframe: i.e  Almond butter, Peanut butter and Cashew butter in 
# a table format
butter_prices = pd.DataFrame(prices_array.reshape(1, 3), index=["Prices"], columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

        Almond butter  Peanut butter  Cashew butter
Prices             10              8             12

In [42]:
product_sold, product_sold.shape

(array([[12, 15,  0],
        [ 3,  3,  7],
        [ 9, 19, 18],
        [ 4,  6, 12],
        [ 1,  6,  7]], dtype=int32),
 (5, 3))

In [43]:
prices_array, prices_array.shape

(array([10,  8, 12]), (3,))

In [44]:
# 5) This is just multiplying the arrays to see if it will give corresponding values
total_sales = prices_array.dot(product_sold)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [45]:
total_sales = prices_array.dot(product_sold.T)
total_sales

array([240, 138, 458, 232, 142])

In [46]:
# This is the main calculation of the daily sales
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

        Mon  Tues  Wed  Thurs  Fri
Prices  240   138  458    232  142

In [47]:
# 6) Now adding it to the weekly_sales column by the right hand side
weekly_sales["Total ($)"] = daily_sales

ValueError: Cannot set a DataFrame with multiple columns to the single column Total ($)

In [51]:
daily_sales

        Mon  Tues  Wed  Thurs  Fri
Prices  240   138  458    232  142

In [54]:
# We got error above bcos the shape of daily_sales is (1, 5), but we want it in (5, 1) as the
# column in weekly_sales. So we will need to transpose the daily_sales
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

       Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

# 016 Turn Images Into NumPy Arrays

In [58]:
 # To view a picture, we do <img src="images/panda.png" /> and change it to a markdown cell and 
# run it as seen below in the nexrt cell

<img src="images/panda.png" />

In [61]:
# Now, We want to turn an image into a NumPy array and this is how we do it
from matplotlib.image import imread
panda = imread("images/panda.png")
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [63]:
panda[:5] # This is taking the first 5 array
# The arrays gotten are the pixel values of colour contained in the panda image

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922],
        [0.16862746, 0.13333334, 0.09803922]]],
      shape=(5, 3500, 3), dtype=float32)

<img src="images/car-photo.png" />

In [64]:
# creating an from car array
car = imread("images/car-photo.png")
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)

In [65]:
car[:5]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.48235294, 0.3529412 , 1.        ],
        [0.4509804 , 0.49019608, 0.38039216, 1.        ]],

       [[0.40392157, 0.3882353 , 0.36078432, 1.        ],
        [0.41960785, 0.41960785, 0.39607844, 1.        ],
        [0.5137255 , 0.5372549 , 0.50980395, 1.        ],
        ...,
        [0.41568628, 0.41960785, 0.28235295, 1.        ],
        [0.4392157 , 0.4627451 , 0.3019608 , 1.        ],
        [0.48235294, 0.5254902 , 0.37254903, 1.        ]],

       [[0.41568628, 0.40784314, 0.38431373, 1.        ],
        [0.54901963, 0.5647059 , 0.5372549 , 1.        ],
        [0.65882355, 0.7019608 , 0.6627451 , 1.        ],
        ...,
        [0.42745098, 0.41960785, 0.31764707, 1.        ],
        [0.42352942, 0.43137255, 0.29803923, 1.        ],
        [0.4509804 , 0.47843137, 0.32941177, 1.        ]]],
      shape=(5, 575, 4), dtype=float32)

In [ ]:
# creating an array from dog photo
dog = imread("images/dog-photo.png")
dog.size, dog.shape, dog.ndim